/*
 * This file was automatically generated by EvoSuite
 */

package org.bank.facade;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import org.bank.account.Account;
import org.bank.facade.Facade;

@RunWith(EvoSuiteRunner.class)
public class TestFacade {

  //Test case number: 0
  /*
   * 2 covered goals:
   * 1 org.bank.facade.Facade.withdraw(Lorg/bank/account/Account;Ljava/lang/Double;)Z: root-Branch
   * 2 org.bank.facade.Facade.<init>()V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      Facade facade0 = new Facade();
      Account account0 = new Account();
      Double double0 = Double.valueOf(1184);
      boolean boolean0 = facade0.withdraw(account0, double0);
      assertEquals(false, boolean0);
  }
}
