/*
 * This file was automatically generated by EvoSuite
 */

package org.bank.gui;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import org.bank.account.Account;
import org.bank.client.Client;
import org.bank.gui.GUI;

@RunWith(EvoSuiteRunner.class)
public class TestGUI {

  //Test case number: 0
  /*
   * 3 covered goals:
   * 1 org.bank.gui.GUI.withdrawView(Lorg/bank/client/Client;)Z: root-Branch
   * 2 org.bank.gui.GUI.<init>()V: root-Branch
   * 3 org.bank.gui.GUI.withdrawValidation(Lorg/bank/client/Client;D)Z: I15 Branch 1 IFEQ L27 - false
   */
  @Test
  public void test0()  throws Throwable  {
      GUI gUI0 = new GUI();
      Account account0 = new Account(1, 1);
      Client client0 = new Client("Conta [ag=", "Conta [ag=", account0);
      boolean boolean0 = gUI0.withdrawView(client0);
      assertEquals("Client [name=Conta [ag=, conta=Conta [ag=1, cc=1, balance=-50.0]]", client0.toString());
      assertEquals(true, boolean0);
  }

  //Test case number: 1
  /*
   * 1 covered goal:
   * 1 org.bank.gui.GUI.withdrawValidation(Lorg/bank/client/Client;D)Z: I15 Branch 1 IFEQ L27 - true
   */
  @Test
  public void test1()  throws Throwable  {
      GUI gUI0 = new GUI();
      Client client0 = new Client("", "", (Account) null);
      boolean boolean0 = gUI0.withdrawValidation(client0, 1796.6175366126079);
      assertEquals(false, boolean0);
  }
}
