/*
 * This file was automatically generated by EvoSuite
 */

package org.bank.account;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import org.bank.account.Account;
import org.bank.client.Client;

@RunWith(EvoSuiteRunner.class)
public class TestAccount {

  //Test case number: 0
  /*
   * 2 covered goals:
   * 1 org.bank.account.Account.setAg(I)V: root-Branch
   * 2 org.bank.account.Account.<init>(II)V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      Account account0 = new Account((-1), (-1));
      account0.setAg((-1));
      assertEquals("Conta [ag=-1, cc=-1, balance=0.0]", account0.toString());
  }

  //Test case number: 1
  /*
   * 1 covered goal:
   * 1 org.bank.account.Account.<init>(IILorg/bank/client/Client;D)V: root-Branch
   */
  @Test
  public void test1()  throws Throwable  {
      Account account0 = new Account((-1), (-1));
      Client client0 = new Client("4qr<kgLS4 =6R#E", "4qr<kgLS4 =6R#E", account0);
      Account account1 = new Account((-1), (-1), client0, (double) (-1));
      assertEquals("Conta [ag=-1, cc=-1, balance=-1.0]", account1.toString());
      assertEquals("Client [name=4qr<kgLS4 =6R#E, conta=Conta [ag=-1, cc=-1, balance=0.0]]", client0.toString());
  }

  //Test case number: 2
  /*
   * 2 covered goals:
   * 1 org.bank.account.Account.getBalance()D: root-Branch
   * 2 org.bank.account.Account.transferir(Ljava/lang/Double;Lorg/bank/account/Account;)Z: I7 Branch 1 IFLT L30 - true
   */
  @Test
  public void test2()  throws Throwable  {
      Account account0 = new Account((-1), (-1));
      Double double0 = Double.valueOf(1.0);
      boolean boolean0 = account0.transferir(double0, account0);
      assertEquals(0.0, account0.getBalance(), 0.01D);
      assertEquals("Conta [ag=-1, cc=-1, balance=0.0]", account0.toString());
      assertEquals(false, boolean0);
  }

  //Test case number: 3
  /*
   * 1 covered goal:
   * 1 org.bank.account.Account.toString()Ljava/lang/String;: root-Branch
   */
  @Test
  public void test3()  throws Throwable  {
      Account account0 = new Account((-1), (-1));
      String string0 = account0.toString();
      assertEquals("Conta [ag=-1, cc=-1, balance=0.0]", account0.toString());
      assertNotNull(string0);
      assertEquals("Conta [ag=-1, cc=-1, balance=0.0]", string0);
  }

  //Test case number: 4
  /*
   * 1 covered goal:
   * 1 org.bank.account.Account.setCc(I)V: root-Branch
   */
  @Test
  public void test4()  throws Throwable  {
      Account account0 = new Account((-1), (-1));
      assertEquals(-1, account0.getCc());
      
      account0.setCc(0);
      assertEquals("Conta [ag=-1, cc=0, balance=0.0]", account0.toString());
      assertEquals(0, account0.getCc());
  }

  //Test case number: 5
  /*
   * 1 covered goal:
   * 1 org.bank.account.Account.getAg()I: root-Branch
   */
  @Test
  public void test5()  throws Throwable  {
      Account account0 = new Account((-1), (-1));
      int int0 = account0.getAg();
      assertEquals(-1, account0.getAg());
      assertEquals("Conta [ag=-1, cc=-1, balance=0.0]", account0.toString());
      assertEquals((-1), int0);
  }

  //Test case number: 6
  /*
   * 2 covered goals:
   * 1 org.bank.account.Account.deposito(D)Z: root-Branch
   * 2 org.bank.account.Account.<init>()V: root-Branch
   */
  @Test
  public void test6()  throws Throwable  {
      Account account0 = new Account();
      boolean boolean0 = account0.deposito((-1388.7850077284756));
      assertEquals((-1388.7850077284756), account0.getBalance(), 0.01D);
      assertEquals(true, boolean0);
  }

  //Test case number: 7
  /*
   * 1 covered goal:
   * 1 org.bank.account.Account.getCc()I: root-Branch
   */
  @Test
  public void test7()  throws Throwable  {
      Account account0 = new Account((-1), (-1));
      int int0 = account0.getCc();
      assertEquals(-1, account0.getCc());
      assertEquals("Conta [ag=-1, cc=-1, balance=0.0]", account0.toString());
      assertEquals((-1), int0);
  }

  //Test case number: 8
  /*
   * 4 covered goals:
   * 1 org.bank.account.Account.setBalance(D)V: root-Branch
   * 2 org.bank.account.Account.transferir(Ljava/lang/Double;Lorg/bank/account/Account;)Z: I7 Branch 1 IFLT L30 - false
   * 3 org.bank.account.Account.debito(D)Z: I6 Branch 2 IFLT L43 - false
   * 4 org.bank.account.Account.sacar(D)Z: I5 Branch 3 IFGT L51 - false
   */
  @Test
  public void test8()  throws Throwable  {
      Account account0 = new Account((-1), (-1));
      account0.sacar((-863.7454728316975));
      Double double0 = Double.valueOf(1.0);
      boolean boolean0 = account0.transferir(double0, account0);
      assertEquals(863.7454728316975, account0.getBalance(), 0.01D);
      assertEquals(true, boolean0);
  }

  //Test case number: 9
  /*
   * 1 covered goal:
   * 1 org.bank.account.Account.debito(D)Z: I6 Branch 2 IFLT L43 - true
   */
  @Test
  public void test9()  throws Throwable  {
      Account account0 = new Account();
      boolean boolean0 = account0.debito(392.3298370084708);
      assertEquals(0.0, account0.getBalance(), 0.01D);
      assertEquals(false, boolean0);
  }

  //Test case number: 10
  /*
   * 1 covered goal:
   * 1 org.bank.account.Account.sacar(D)Z: I5 Branch 3 IFGT L51 - true
   */
  @Test
  public void test10()  throws Throwable  {
      Account account0 = new Account();
      boolean boolean0 = account0.sacar(1482.7591375786253);
      assertEquals(false, boolean0);
  }
}
