/*
 * This file was automatically generated by EvoSuite
 */

package org.bank.account;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import org.bank.account.Account;
import org.bank.client.Client;

@RunWith(EvoSuiteRunner.class)
public class TestAccount {

  //Test case number: 0
  /*
   * 2 covered goals:
   * 1 org.bank.account.Account.setAg(I)V: root-Branch
   * 2 org.bank.account.Account.<init>()V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      Account account0 = new Account();
      account0.setAg((-193));
      assertEquals("Conta [ag=-193, cc=0, balance=0.0]", account0.toString());
      assertEquals(-193, account0.getAg());
  }

  //Test case number: 1
  /*
   * 1 covered goal:
   * 1 org.bank.account.Account.<init>(IILorg/bank/client/Client;D)V: root-Branch
   */
  @Test
  public void test1()  throws Throwable  {
      Account account0 = new Account();
      Client client0 = new Client("", account0);
      Account account1 = new Account(0, 1855, client0, 618.0471094734193);
      assertEquals("Conta [ag=0, cc=1855, balance=618.0471094734193]", account1.toString());
  }

  //Test case number: 2
  /*
   * 5 covered goals:
   * 1 org.bank.account.Account.getBalance()D: root-Branch
   * 2 org.bank.account.Account.setBalance(D)V: root-Branch
   * 3 org.bank.account.Account.<init>(II)V: root-Branch
   * 4 org.bank.account.Account.transferir(Ljava/lang/Double;Lorg/bank/account/Account;)Z: I7 Branch 1 IFLT L30 - false
   * 5 org.bank.account.Account.debito(D)Z: I6 Branch 2 IFLT L43 - false
   */
  @Test
  public void test2()  throws Throwable  {
      Account account0 = new Account((-619), (-1370));
      Double double0 = Double.valueOf(0.0);
      boolean boolean0 = account0.transferir(double0, account0);
      assertEquals(0.0, account0.getBalance(), 0.01D);
      assertEquals(true, boolean0);
      assertEquals("Conta [ag=-619, cc=-1370, balance=0.0]", account0.toString());
  }

  //Test case number: 3
  /*
   * 1 covered goal:
   * 1 org.bank.account.Account.toString()Ljava/lang/String;: root-Branch
   */
  @Test
  public void test3()  throws Throwable  {
      Account account0 = new Account((-619), (-1370));
      String string0 = account0.toString();
      assertNotNull(string0);
      assertEquals("Conta [ag=-619, cc=-1370, balance=0.0]", account0.toString());
      assertEquals("Conta [ag=-619, cc=-1370, balance=0.0]", string0);
  }

  //Test case number: 4
  /*
   * 1 covered goal:
   * 1 org.bank.account.Account.setCc(I)V: root-Branch
   */
  @Test
  public void test4()  throws Throwable  {
      Account account0 = new Account();
      account0.setCc(469);
      assertEquals(469, account0.getCc());
      assertEquals("Conta [ag=0, cc=469, balance=0.0]", account0.toString());
  }

  //Test case number: 5
  /*
   * 1 covered goal:
   * 1 org.bank.account.Account.getAg()I: root-Branch
   */
  @Test
  public void test5()  throws Throwable  {
      Account account0 = new Account();
      int int0 = account0.getAg();
      assertEquals(0, account0.getAg());
      assertEquals(0, int0);
  }

  //Test case number: 6
  /*
   * 1 covered goal:
   * 1 org.bank.account.Account.getCc()I: root-Branch
   */
  @Test
  public void test6()  throws Throwable  {
      Account account0 = new Account();
      int int0 = account0.getCc();
      assertEquals(0, account0.getCc());
      assertEquals(0, int0);
  }

  //Test case number: 7
  /*
   * 1 covered goal:
   * 1 org.bank.account.Account.deposito(D)Z: root-Branch
   */
  @Test
  public void test7()  throws Throwable  {
      Account account0 = new Account();
      boolean boolean0 = account0.deposito((-1));
      assertEquals("Conta [ag=0, cc=0, balance=-1.0]", account0.toString());
      assertEquals(true, boolean0);
  }

  //Test case number: 8
  /*
   * 1 covered goal:
   * 1 org.bank.account.Account.transferir(Ljava/lang/Double;Lorg/bank/account/Account;)Z: I7 Branch 1 IFLT L30 - true
   */
  @Test
  public void test8()  throws Throwable  {
      Account account0 = new Account();
      boolean boolean0 = account0.transferir(1.7976931348623157E308, account0);
      assertEquals(false, boolean0);
      assertEquals(0.0, account0.getBalance(), 0.01D);
  }

  //Test case number: 9
  /*
   * 1 covered goal:
   * 1 org.bank.account.Account.debito(D)Z: I6 Branch 2 IFLT L43 - true
   */
  @Test
  public void test9()  throws Throwable  {
      Account account0 = new Account();
      boolean boolean0 = account0.debito(1);
      assertEquals(0.0, account0.getBalance(), 0.01D);
      assertEquals(false, boolean0);
  }

  //Test case number: 10
  /*
   * 1 covered goal:
   * 1 org.bank.account.Account.sacar(D)Z: I5 Branch 3 IFGT L51 - true
   */
  @Test
  public void test10()  throws Throwable  {
      Account account0 = new Account(1683, 1683);
      boolean boolean0 = account0.sacar(1110.3840639673274);
      assertEquals("Conta [ag=1683, cc=1683, balance=0.0]", account0.toString());
      assertEquals(false, boolean0);
  }

  //Test case number: 11
  /*
   * 1 covered goal:
   * 1 org.bank.account.Account.sacar(D)Z: I5 Branch 3 IFGT L51 - false
   */
  @Test
  public void test11()  throws Throwable  {
      Account account0 = new Account();
      boolean boolean0 = account0.sacar((-1895.3817602359418));
      assertEquals("Conta [ag=0, cc=0, balance=1895.3817602359418]", account0.toString());
      assertEquals(true, boolean0);
  }
}
