/*
 * This file was automatically generated by EvoSuite
 */

package org.bank.client;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import org.bank.account.Account;
import org.bank.client.Client;

@RunWith(EvoSuiteRunner.class)
public class TestClient {

  //Test case number: 0
  /*
   * 2 covered goals:
   * 1 org.bank.client.Client.getName()Ljava/lang/String;: root-Branch
   * 2 org.bank.client.Client.<init>(Ljava/lang/String;Ljava/lang/String;Lorg/bank/account/Account;)V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      Account account0 = new Account();
      Client client0 = new Client("k", "k", account0);
      String string0 = client0.getName();
      assertEquals("Client [name=k, conta=Conta [ag=0, cc=0, balance=0.0]]", client0.toString());
      assertNotNull(string0);
  }

  //Test case number: 1
  /*
   * 2 covered goals:
   * 1 org.bank.client.Client.getAccount()Lorg/bank/account/Account;: root-Branch
   * 2 org.bank.client.Client.<init>(Ljava/lang/String;Lorg/bank/account/Account;)V: root-Branch
   */
  @Test
  public void test1()  throws Throwable  {
      Account account0 = new Account();
      Client client0 = new Client("M?<{L%4}rJ6/C", account0);
      Account account1 = client0.getAccount();
      assertEquals("Client [name=M?<{L%4}rJ6/C, conta=Conta [ag=0, cc=0, balance=0.0]]", client0.toString());
      assertNotNull(account1);
  }

  //Test case number: 2
  /*
   * 1 covered goal:
   * 1 org.bank.client.Client.setPhone(Ljava/lang/String;)V: root-Branch
   */
  @Test
  public void test2()  throws Throwable  {
      Account account0 = new Account(1718, 1718);
      Client client0 = new Client("+by~s~(H}0b:N|*(saY", "+by~s~(H}0b:N|*(saY", account0);
      client0.setPhone((String) null);
      assertEquals("Client [name=+by~s~(H}0b:N|*(saY, conta=Conta [ag=1718, cc=1718, balance=0.0]]", client0.toString());
  }

  //Test case number: 3
  /*
   * 1 covered goal:
   * 1 org.bank.client.Client.setName(Ljava/lang/String;)V: root-Branch
   */
  @Test
  public void test3()  throws Throwable  {
      Account account0 = new Account(1718, 1718);
      Client client0 = new Client("+by~s~(H}0b:N|*(saY", "+by~s~(H}0b:N|*(saY", account0);
      client0.setName("");
      assertEquals("Client [name=, conta=Conta [ag=1718, cc=1718, balance=0.0]]", client0.toString());
  }

  //Test case number: 4
  /*
   * 1 covered goal:
   * 1 org.bank.client.Client.setAccount(Lorg/bank/account/Account;)V: root-Branch
   */
  @Test
  public void test4()  throws Throwable  {
      Account account0 = new Account();
      Client client0 = new Client((String) null, (String) null, account0);
      assertEquals("Client [name=null, conta=Conta [ag=0, cc=0, balance=0.0]]", client0.toString());
      
      client0.setAccount(account0);
  }

  //Test case number: 5
  /*
   * 1 covered goal:
   * 1 org.bank.client.Client.toString()Ljava/lang/String;: root-Branch
   */
  @Test
  public void test5()  throws Throwable  {
      Account account0 = new Account(1718, 1718);
      Client client0 = new Client("+by~s~(H}0b:N|*(saY", "+by~s~(H}0b:N|*(saY", account0);
      String string0 = client0.toString();
      assertNotNull(string0);
      assertEquals("Client [name=+by~s~(H}0b:N|*(saY, conta=Conta [ag=1718, cc=1718, balance=0.0]]", client0.toString());
      assertEquals("Client [name=+by~s~(H}0b:N|*(saY, conta=Conta [ag=1718, cc=1718, balance=0.0]]", string0);
  }

  //Test case number: 6
  /*
   * 1 covered goal:
   * 1 org.bank.client.Client.getPhone()Ljava/lang/String;: root-Branch
   */
  @Test
  public void test6()  throws Throwable  {
      Account account0 = new Account();
      Client client0 = new Client("M?<{L%4}rJ6/C", account0);
      String string0 = client0.getPhone();
      assertEquals("Client [name=M?<{L%4}rJ6/C, conta=Conta [ag=0, cc=0, balance=0.0]]", client0.toString());
      assertNull(string0);
  }
}
